version: '2.0'

services:
  servermysql:
    build:
      context: Server
      dockerfile: Dockerfile
      args:
        - DB=MySQL
    restart: always
    ports:
    - "6001:6000"
    networks:
    - mysql
    links:
    - "mysql:mysql"
    depends_on:
    - mysql

  servermongodb:
    build:
      context: Server
      dockerfile: Dockerfile
      args:
        - DB=MongoDB
    restart: always
    ports:
    - "6002:6000"
    networks:
    - mongo
    links:
    - "mongodb:mongodb"
    depends_on:
    - mongodb

  mysql:
    image: mysql:5.5
    restart: always
    networks:
    - mysql
    environment:
    - MYSQL_ROOT_PASSWORD=bla
    - MYSQL_ROOT_HOST=172.18.0.3
    - MYSQL_DATABASE=test
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    ports:
    - "3306:3306"
    volumes:
    - ./mysql-data:/var/lib/mysql

  mongodb:
    image: mongo
    restart: always
    networks:
    - mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5000:5000"
    depends_on:
    - servermysql
    - servermongodb
    volumes: 
    - npm-cache:/root/.npm

volumes:
  npm-cache:
    external: false

networks:
  mysql:
    driver: bridge
  mongo:
    driver: bridge